#server:
#  port: 8443
  #keytool -genkey -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3652
#  ssl:
#    key-store: keystore.p12
#    key-store-password: secret
spring:
  jmx:
    enable: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:h2:./registrator
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#     enabled: true
#logging:
#  level:
##    root: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#      apache:
#        coyote:
#          http11:
#            Http11InputBuffer: DEBUG
#    medvedev:
#      ilya:
#        example:
#          spring:
#            data:
#              jpa:
#                registrator: DEBUG